name: QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: install tools
        run: |
          sudo apt update
          sudo apt install -y clang-format
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{runner.os}}-pre-commit
      - name: install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install tools
        run: |
          sudo apt update
          sudo apt install -y cmake
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: latest
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: init sdk
        run: git -C vendor/pico-sdk submodule update --init
      - id: build-release
        name: build release
        run: |
          mkdir build-release
          cd build-release
          cmake ../
          make
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: build host
        run: |
          cmake -DHOST_BUILD=YES -B cmake-build-host
          make -C cmake-build-host
      - name: run tests
        run: |
          make -C cmake-build-host ARGS="-V" test
